### PR TITLE
add default and examples to annotations

### PR DESCRIPTION
**Pull request by arnedesmedt**
https://json-schema.org/understanding-json-schema/reference/generic.html#annotations

### CODE REVIEW

**Comment by arnedesmedt** [comment]
This creates the possibility for the opis validator to add some default values.
https://github.com/event-engine/php-json-schema/blob/master/src/OpisJsonSchema.php#L38

After validation the $enforcedObjectData contains the default values. But I don't know what could be the best way to get that data back into the payload. Do you guys have any idea?

**Comment by arnedesmedt** [comment]
The other library also can handle default values (https://github.com/justinrainbow/json-schema#default-values). So we could return the stdClass as an array in the assert method, but that's maybe a bit confusing, because you expect that an assert method only throws exceptions if an assertion is not met?

**Comment by codeliner** [comment]
Good question @arnedesmedt ! I'll look at it tomorrow. Maybe I find a way.

**Comment by codeliner** [comment]
short update on this: I did not find the time yet to think about a solution due to a lot of work on my desk. But it has a high priority on my open source todo list! Sorry for the delay. I need a few more days.

**Comment by arnedesmedt** [comment]
No problem, If there is something I can help with to implement this feature, just mention me here :stuck_out_tongue:

**Comment by arnedesmedt** [comment]
Hi @codeliner,

Can this already been merged? I've already found a temporary solution to load the default data in the the payload, but it's not stable.

Maybe an issue can be opened to add default values in the payload?

Greetings,
Arne

**Review by codeliner — APPROVED** [review]

**Comment by codeliner** [comment]
Wow, my last comment is one month ago. Sorry for that! I still have the issue on my to do, but time is running really fast.

Ok let's merge it as-is. I create a follow up :+1:

**Pull request merged**
